### ISSUE TITLE
generate_instruction.py报错

### ISSUE THREAD

**Issue by MingJiaAn** [LianjiaTech/BELLE#11]
Traceback (most recent call last):
  File "generate_instruction.py", line 24, in <module>
    import utils
  File "/mnt/amj/chatgpt/BELLE/utils.py", line 40, in <module>
    prompts: Union[str, Sequence[str], Sequence[dict[str, str]], dict[str, str]],
TypeError: 'type' object is not subscriptable
(chatgpt) [root@iZ2zecged3txs683zzjfnpZ BELLE]# python3 generate_instruction.py generate_instruction_following_data --api=chat --model_name=gpt-3.5-turbo
Traceback (most recent call last):
  File "generate_instruction.py", line 24, in <module>
    import utils
  File "/mnt/amj/chatgpt/BELLE/utils.py", line 40, in <module>
    prompts: Union[str, Sequence[str], Sequence[dict[str, str]], dict[str, str]],
TypeError: 'type' object is not subscriptable

麻烦看下如何解决

**Comment by Monstarrr** [comment]
这个好像是python的版本问题，更新python版本或者from __future__ import annotations

**Comment by bestpredicts** [comment]
> 这个好像是python的版本问题，更新python版本或者from **future** import annotations

应该是python版本的问题。我这里python3.9下面执行没问题。
