### ISSUE TITLE
运行量化模型报错Exception: expected value at line 1 column 1

### ISSUE THREAD

**Issue by lihan1719** [LianjiaTech/BELLE#114]
我按照gptq目录下的readme安装配置后，运行:
```
UDA_VISIBLE_DEVICES=0 python bloom_inference.py BELLE-7B-gptq --wbits 8 --groupsize 128 --load BELLE-7B-gptq/bloom7b-2m-8bit-128g.pt --text "hello"
```
报错如下:
```
Loading model ...
Done.
Traceback (most recent call last):
  File "/home/lihan/桌面/BELLE/gptq/bloom_inference.py", line 118, in <module>
    tokenizer = AutoTokenizer.from_pretrained(args.model)
  File "/home/lihan/miniconda/envs/gptq/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 694, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/lihan/miniconda/envs/gptq/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/home/lihan/miniconda/envs/gptq/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/lihan/miniconda/envs/gptq/lib/python3.9/site-packages/transformers/models/bloom/tokenization_bloom_fast.py", line 121, in __init__
    super().__init__(
  File "/home/lihan/miniconda/envs/gptq/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: expected value at line 1 column 1
```

运行主机显卡是3060 12G显存和64G内存

可以帮我看看那里出错了吗，我看了原来的issue提过这个错误，和我这个好像不一样。

**Comment by mabaochang** [comment]
看起来像是tokenizer.json文件有问题，可以确认下文件大小和md5值

**Comment by lihan1719** [comment]
感谢，解决了，问题出在 tokenizer.json这个文件上，不知道原因出在哪，我直接使用git clone下载模型
[BELLE-7B-gptq](https://huggingface.co/BelleGroup/BELLE-7B-gptq)的时候,okenizer.json只被下载了一小部分数据，替换完整的文件后就可以跑通了。
