### ISSUE TITLE
RuntimeError: Error building extension 'fused_adam'

### ISSUE THREAD

**Issue by tianbuwei** [LianjiaTech/BELLE#150]
start train...
2023-04-11 14:24:52 - finetune.py[line:176] - INFO: num_gpus = 2, training_nums = 519255, t_total = 115390, warmup_steps = 11539
start train...
2023-04-11 14:24:55 - finetune.py[line:176] - INFO: num_gpus = 2, training_nums = 519255, t_total = 115390, warmup_steps = 11539
[2023-04-11 14:24:55,314] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
trainer.train
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
trainer.train
Using /home/sl_tyrc/.cache/torch_extensions/py310_cu116 as PyTorch extensions root...
Using /home/sl_tyrc/.cache/torch_extensions/py310_cu116 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/sl_tyrc/.cache/torch_extensions/py310_cu116/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /data/gengzk/miniconda3/envs/tianhs-Belle/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/include -isystem /data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/include/TH -isystem /data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/include/THC -isystem /data/gengzk/miniconda3/envs/tianhs-Belle/include -isystem /data/gengzk/miniconda3/envs/tianhs-Belle/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_80,code=compute_80 -std=c++14 -c /data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o
[2/2] c++ fused_adam_frontend.o multi_tensor_adam.cuda.o -shared -L/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/data/gengzk/miniconda3/envs/tianhs-Belle/lib64 -lcudart -o fused_adam.so
FAILED: fused_adam.so
c++ fused_adam_frontend.o multi_tensor_adam.cuda.o -shared -L/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/data/gengzk/miniconda3/envs/tianhs-Belle/lib64 -lcudart -o fused_adam.so
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: 找不到 -lcudart
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/gengzk/tianhs/BELLE/train/finetune.py", line 237, in <module>
    train(args)
  File "/data/gengzk/tianhs/BELLE/train/finetune.py", line 215, in train
    trainer.train(resume_from_checkpoint = args.resume_from_checkpoint)
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 340, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1283, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1360, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/ops/adam/fused_adam.py", line 73, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 485, in load
    return self.jit_load(verbose)
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 520, in jit_load
    op_module = load(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused_adam'
Loading extension module fused_adam...
Traceback (most recent call last):
  File "/data/gengzk/tianhs/BELLE/train/finetune.py", line 237, in <module>
    train(args)
  File "/data/gengzk/tianhs/BELLE/train/finetune.py", line 215, in train
    trainer.train(resume_from_checkpoint = args.resume_from_checkpoint)
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 340, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1283, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1360, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/ops/adam/fused_adam.py", line 73, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 485, in load
    return self.jit_load(verbose)
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 520, in jit_load
    op_module = load(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1534, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/data/gengzk/miniconda3/envs/tianhs-Belle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1936, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: /home/sl_tyrc/.cache/torch_extensions/py310_cu116/fused_adam/fused_adam.so: cannot open shared object file: No such file or directory

我的环境配置：
(tianhs-Belle) sl_tyrc@hngpu07:/data/gengzk/tianhs/BELLE/train$ pip list
Package            Version
------------------ -----------
accelerate         0.17.1
aiohttp            3.8.4
aiosignal          1.3.1
appdirs            1.4.4
async-timeout      4.0.2
attrs              22.2.0
bitsandbytes       0.37.2
brotlipy           0.7.0
certifi            2022.12.7
cffi               1.15.1
charset-normalizer 3.1.0
click              8.1.3
cryptography       39.0.0
cupy               10.4.0
datasets           2.11.0
deepspeed          0.8.3
dill               0.3.6
docker-pycreds     0.4.0
faiss              1.7.2
fastparquet        0.5.0
fastrlock          0.8
filelock           3.11.0
fire               0.5.0
frozenlist         1.3.3
fsspec             2023.4.0
gitdb              4.0.10
GitPython          3.1.31
hjson              3.1.0
huggingface-hub    0.13.4
idna               3.4
llvmlite           0.39.1
loguru             0.6.0
multidict          6.0.4
multiprocess       0.70.14
netifaces          0.11.0
ninja              1.11.1
numba              0.56.4
numpy              1.21.6
packaging          23.0
pandas             2.0.0
pathtools          0.1.2
peft               0.3.0.dev0
Pillow             9.4.0
pip                22.3.1
protobuf           4.22.1
psutil             5.9.4
py-cpuinfo         9.0.0
pyarrow            8.0.0
pycparser          2.21
pydantic           1.10.7
pyOpenSSL          23.1.1
PySocks            1.7.1
python-dateutil    2.8.2
python-snappy      0.6.1
pytz               2023.3
PyYAML             6.0
regex              2023.3.23
requests           2.28.2
responses          0.18.0
sentencepiece      0.1.97
sentry-sdk         1.19.1
setproctitle       1.3.2
setuptools         67.6.1
six                1.16.0
smmap              5.0.0
some-package       0.1
termcolor          2.2.0
thrift             0.18.1
tokenizers         0.13.3
torch              1.13.1
torchaudio         0.13.1
torchvision        0.14.1
tqdm               4.65.0
transformers       4.28.0.dev0
typing_extensions  4.5.0
tzdata             2023.3
urllib3            1.26.15
wandb              0.13.10
wheel              0.40.0
xxhash             3.2.0
yarl               1.8.2
zstandard          0.20.0

您好，我在训练过程中出现这个问题导致无法训练，请问下这个该怎么解决

**Comment by xianghuisun** [comment]
这个是编译so文件时遇到的问题，由于这涉及到您本机环境的问题，我们很难用一个命令给您解决
您可以尝试。conda install -c nvidia libcusolver-dev
如果还是不行，可以参考以下几个文档
https://github.com/microsoft/DeepSpeed/issues/2187
https://github.com/microsoft/DeepSpeed/issues/885
https://www.deepspeed.ai/tutorials/advanced-install/#pre-install-deepspeed-ops

**Comment by shishijier** [comment]
请问你解决这个问题了吗？我也遇见了这个问题，目前还没有解决办法。

**Comment by tianbuwei** [comment]
@shishijier 应该是 cannot find -l cudart 的错误，你软连接一下就行，我是执行的这个命令 sudo ln -s /usr/local/cuda/lib64/libcudart.so /usr/lib/libcudart.so
