### ISSUE TITLE
关于训练好的模型进行inference的问题：weight is on the meta device, we need a `value` to put in on 0.

### ISSUE THREAD

**Issue by Tian14267** [LianjiaTech/BELLE#155]
大神们好，我想问下，我通过 LoRA 训练了一个 Bloom 模型，在进行文本生成时，却提示没有权重。**我的代码**是：
```
python generate.py \
            --dev_file data_dir/Belle_open_source_0.5M.dev.json \
            --model_name_or_path trained_models/bloom/checkpoint-1000
```
**提示加载出错：**
```
CUDA SETUP: CUDA runtime path found: /root/anaconda3/envs/Belle/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 116
/root/anaconda3/envs/Belle/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /root/anaconda3/envs/Belle/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so...
Some weights of the model checkpoint at trained_models/bloom were not used when initializing BloomForCausalLM: ['base_model.model.transformer.h.9.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.13.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.16.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.25.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.2.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.18.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.26.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.8.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.14.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.6.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.12.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.3.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.11.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.17.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.4.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.3.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.17.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.14.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.19.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.21.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.20.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.29.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.22.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.24.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.19.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.20.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.6.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.7.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.22.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.28.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.1.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.21.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.0.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.2.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.23.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.10.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.8.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.15.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.28.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.26.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.5.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.0.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.5.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.9.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.13.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.10.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.11.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.24.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.16.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.27.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.7.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.4.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.18.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.12.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.29.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.1.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.25.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.23.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.h.15.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.h.27.self_attention.query_key_value.lora_B.weight']
- This IS expected if you are initializing BloomForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BloomForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "generate.py", line 139, in <module>
    model = get_model(args.model_name_or_path)
  File "generate.py", line 33, in get_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2787, in from_pretrained
    dispatch_model(model, device_map=device_map, offload_dir=offload_folder, offload_index=offload_index)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/big_modeling.py", line 370, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 471, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/hooks.py", line 244, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/root/anaconda3/envs/Belle/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 136, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: weight is on the meta device, we need a `value` to put in on 0.

```

我添加了 **lora_weights** 之后，还是同样的问题：
```
python generate.py \
            --dev_file data_dir/Belle_open_source_0.5M.dev.json \
            --model_name_or_path trained_models/bloom/checkpoint-1000 \
            --lora_weights trained_models/bloom/checkpoint-1000
```

**请问这是啥情况啊**

**Comment by xianghuisun** [comment]
> trained_models/bloom/checkpoint-1000

model_name_or_path下应该是原始Bloom模型的参数

**Comment by Tian14267** [comment]
> > trained_models/bloom/checkpoint-1000
> 
> model_name_or_path下应该是原始Bloom模型的参数

Thank you ! It's OK.

**Comment by chilljudaoren** [comment]
> > > trained_models/bloom/checkpoint-1000
> > 
> > 
> > model_name_or_path下应该是原始Bloom模型的参数
> 
> Thank you ! It's OK.

这个是什么意思？我还没解决，请问可以帮帮我嘛？
