### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by jinjingzhong** [LianjiaTech/BELLE#158]
我用一张V100运行如下finetune，报错了，请问是什么原因，如何解决，谢谢
deepspeed --num_gpus=1 finetune.py --model_config_file run_config/Llama_config.json  --deepspeed run_config/deepspeed_config.json
或者
CUDA_VISIBLE_DEVICES=0 python finetune.py --model_config_file run_config/Llama_config.json

系统是ubuntu20， cuda 11.6
过程：
读取完checkpoints之后，再读取完examples
然后输出 start train... 然后出错了

2023-04-11 17:38:40 - finetune.py[line:175] - INFO: num_gpus = 1, training_nums = 5192, t_total = 610, warmup_steps = 61
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Traceback (most recent call last):
  File "/home/surfingtech/BELLE-main/train/finetune.py", line 236, in <module>
    train(args)
  File "/home/surfingtech/BELLE-main/train/finetune.py", line 176, in train
    trainer = transformers.Trainer(
  File "/home/surfingtech/BELLE-main/train/transformers-main/src/transformers/trainer.py", line 498, in __init__
    self._move_model_to_device(model, args.device)
  File "/home/surfingtech/BELLE-main/train/transformers-main/src/transformers/trainer.py", line 740, in _move_model_to_device
    model = model.to(device)
  File "/home/surfingtech/BELLE-main/train/transformers-main/src/transformers/modeling_utils.py", line 1888, in to
    return super().to(*args, **kwargs)
  File "/home/surfingtech/.conda/envs/Belle/lib/python3.10/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/home/surfingtech/.conda/envs/Belle/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/surfingtech/.conda/envs/Belle/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/surfingtech/.conda/envs/Belle/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/surfingtech/.conda/envs/Belle/lib/python3.10/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/home/surfingtech/.conda/envs/Belle/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

万分感谢

**Comment by xianghuisun** [comment]
这个问题我这边没有复现出来，不过一张V100的显存在正常参数配置下是无法微调7B模型的全量参数的。

**Comment by jinjingzhong** [comment]
> 这个问题我这边没有复现出来，不过一张V100的显存在正常参数配置下是无法微调7B模型的全量参数的。

哦 谢谢

**Comment by pipinstallyp** [comment]
What was the solution? I'm facing a similar problem now

**Comment by haimianxing** [comment]
I also encountor this problem.I need help.
