### ISSUE TITLE
用 v100  finetune ，提示out of memory，怎么设置成cpu 训练啊

### ISSUE THREAD

**Issue by songxia928** [LianjiaTech/BELLE#211]
```
Traceback (most recent call last):
  File "/BELLE/BELLE-main/train/finetune.py", line 244, in <module>
    train(args)
  File "/BELLE-main/train/finetune.py", line 92, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/anaconda3/envs/Belle4/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/root/anaconda3/envs/Belle4/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2736, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/root/anaconda3/envs/Belle4/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3064, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/root/anaconda3/envs/Belle4/lib/python3.10/site-packages/transformers/modeling_utils.py", line 698, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/root/anaconda3/envs/Belle4/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 149, in set_module_tensor_to_device
    new_value = value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 31.75 GiB total capacity; 19.33 GiB already allocated; 172.69 MiB free; 19.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2023-04-17 06:59:22,991] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 25542
[2023-04-17 06:59:22,991] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 25543
[2023-04-17 06:59:24,059] [ERROR] [launch.py:324:sigkill_handler] ['/root/anaconda3/envs/Belle4/bin/python3.10', '-u', 'finetune.py', '--local_rank=1', '--model_config_file', 'run_config/Bloom_config.json', '--deepspeed', 'run_config/deepspeed_config.json'] exits with return code = 1
```
非 LoRA训练。运行 generate.py 没问题。想跑一下 finetune， cpu 也行。 大佬知道怎么设置啊

**Comment by xianghuisun** [comment]
可参考：https://github.com/microsoft/DeepSpeedExamples/tree/master/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/training_scripts/single_gpu
