### ISSUE TITLE
A100 8卡不能正常运行,但是4卡可以正常运行

### ISSUE THREAD

**Issue by scarydemon2** [LianjiaTech/BELLE#218]
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_type : bloom
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_name_or_path : bigscience/bloomz-7b1-mt
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: data_path : data_dir/train_2M_CN.json
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: output_dir : trained_models/bloom_2M_firefly_hanyui_3epoch
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: batch_size : 256
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: per_device_train_batch_size : 16
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: num_epochs : 3
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: learning_rate : 1.5e-05
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: cutoff_len : 1024
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_size : 1500
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_rate : 0.05
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: save_steps : 1000
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: eval_steps : 1000
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: warmup_steps : 200
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: logging_steps : 30
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: gradient_accumulation_steps : 4
2023-04-18 11:16:25 - finetune-mixdata.py[line:328] - INFO: per_device_train_batch_size = 16, gradient_accumulation_steps = 4
2023-04-18 11:16:25 - finetune-mixdata.py[line:319] - INFO: args.__dict__ : {'model_config_file': 'run_config/Bloom_mix_config.json', 'deepspeed': None, 'resume_from_checkpoint': False, 'train_on_inputs': False, 'lora_hyperparams_file': 'run_config/lora_hyperparams_bloom.json', 'use_lora': True, 'local_rank': None}
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_type : bloom
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_name_or_path : bigscience/bloomz-7b1-mt
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: data_path : data_dir/train_2M_CN.json
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: output_dir : trained_models/bloom_2M_firefly_hanyui_3epoch
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: batch_size : 256
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: per_device_train_batch_size : 16
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: num_epochs : 3
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: learning_rate : 1.5e-05
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: cutoff_len : 1024
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_size : 1500
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_rate : 0.05
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: save_steps : 1000
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: eval_steps : 1000
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: warmup_steps : 200
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: logging_steps : 30
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: gradient_accumulation_steps : 4
2023-04-18 11:16:25 - finetune-mixdata.py[line:328] - INFO: per_device_train_batch_size = 16, gradient_accumulation_steps = 4
Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
2023-04-18 11:16:25 - finetune-mixdata.py[line:319] - INFO: args.__dict__ : {'model_config_file': 'run_config/Bloom_mix_config.json', 'deepspeed': None, 'resume_from_checkpoint': False, 'train_on_inputs': False, 'lora_hyperparams_file': 'run_config/lora_hyperparams_bloom.json', 'use_lora': True, 'local_rank': None}
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_type : bloom
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_name_or_path : bigscience/bloomz-7b1-mt
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: data_path : data_dir/train_2M_CN.json
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: output_dir : trained_models/bloom_2M_firefly_hanyui_3epoch
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: batch_size : 256
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: per_device_train_batch_size : 16
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: num_epochs : 3
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: learning_rate : 1.5e-05
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: cutoff_len : 1024
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_size : 1500
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_rate : 0.05
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: save_steps : 1000
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: eval_steps : 1000
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: warmup_steps : 200
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: logging_steps : 30
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: gradient_accumulation_steps : 4
2023-04-18 11:16:25 - finetune-mixdata.py[line:328] - INFO: per_device_train_batch_size = 16, gradient_accumulation_steps = 4
Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
2023-04-18 11:16:25 - finetune-mixdata.py[line:319] - INFO: args.__dict__ : {'model_config_file': 'run_config/Bloom_mix_config.json', 'deepspeed': None, 'resume_from_checkpoint': False, 'train_on_inputs': False, 'lora_hyperparams_file': 'run_config/lora_hyperparams_bloom.json', 'use_lora': True, 'local_rank': None}
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_type : bloom
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_name_or_path : bigscience/bloomz-7b1-mt
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: data_path : data_dir/train_2M_CN.json
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: output_dir : trained_models/bloom_2M_firefly_hanyui_3epoch
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: batch_size : 256
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: per_device_train_batch_size : 16
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: num_epochs : 3
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: learning_rate : 1.5e-05
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: cutoff_len : 1024
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_size : 1500
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_rate : 0.05
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: save_steps : 1000
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: eval_steps : 1000
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: warmup_steps : 200
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: logging_steps : 30
2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: gradient_accumulation_steps : 4
2023-04-18 11:16:25 - finetune-mixdata.py[line:328] - INFO: per_device_train_batch_size = 16, gradient_accumulation_steps = 4
Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
Loading checkpoint shards:   0%|                                                                                                                                               | 0/4 [00:00<?, ?it/s]Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
Loading checkpoint shards:   0%|                                                                                                                                               | 0/4 [00:00<?, ?it/s]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2947 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2948 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2949 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2951 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2952 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2954 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 3 (pid: 2950) of binary: /usr/local/anaconda3/bin/python
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by scarydemon2** [comment]
在加载模型这一步报错，但是指定--nproc_per_node=4之后模型就可以正常加载。BLOOMZ模型我首先加载到CPU然后执行save_pretrained保存到本地。模型文件夹包含4个.bin文件，不知道是否与GPU数量相关？

**Comment by xianghuisun** [comment]
--nproc_per_node=8就报错嘛，请问你试过加载LLaMA模型嘛

**Comment by scarydemon2** [comment]
> --nproc_per_node=8就报错嘛，请问你试过加载LLaMA模型嘛

是的。没试过，只是过7B的bloomz

**Comment by xianghuisun** [comment]
> 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_type : bloom 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_name_or_path : bigscience/bloomz-7b1-mt 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: data_path : data_dir/train_2M_CN.json 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: output_dir : trained_models/bloom_2M_firefly_hanyui_3epoch 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: batch_size : 256 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: per_device_train_batch_size : 16 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: num_epochs : 3 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: learning_rate : 1.5e-05 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: cutoff_len : 1024 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_size : 1500 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_rate : 0.05 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: save_steps : 1000 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: eval_steps : 1000 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: warmup_steps : 200 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: logging_steps : 30 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: gradient_accumulation_steps : 4 2023-04-18 11:16:25 - finetune-mixdata.py[line:328] - INFO: per_device_train_batch_size = 16, gradient_accumulation_steps = 4 2023-04-18 11:16:25 - finetune-mixdata.py[line:319] - INFO: args.**dict** : {'model_config_file': 'run_config/Bloom_mix_config.json', 'deepspeed': None, 'resume_from_checkpoint': False, 'train_on_inputs': False, 'lora_hyperparams_file': 'run_config/lora_hyperparams_bloom.json', 'use_lora': True, 'local_rank': None} 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_type : bloom 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_name_or_path : bigscience/bloomz-7b1-mt 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: data_path : data_dir/train_2M_CN.json 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: output_dir : trained_models/bloom_2M_firefly_hanyui_3epoch 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: batch_size : 256 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: per_device_train_batch_size : 16 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: num_epochs : 3 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: learning_rate : 1.5e-05 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: cutoff_len : 1024 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_size : 1500 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_rate : 0.05 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: save_steps : 1000 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: eval_steps : 1000 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: warmup_steps : 200 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: logging_steps : 30 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: gradient_accumulation_steps : 4 2023-04-18 11:16:25 - finetune-mixdata.py[line:328] - INFO: per_device_train_batch_size = 16, gradient_accumulation_steps = 4 Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning. 2023-04-18 11:16:25 - finetune-mixdata.py[line:319] - INFO: args.**dict** : {'model_config_file': 'run_config/Bloom_mix_config.json', 'deepspeed': None, 'resume_from_checkpoint': False, 'train_on_inputs': False, 'lora_hyperparams_file': 'run_config/lora_hyperparams_bloom.json', 'use_lora': True, 'local_rank': None} 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_type : bloom 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_name_or_path : bigscience/bloomz-7b1-mt 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: data_path : data_dir/train_2M_CN.json 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: output_dir : trained_models/bloom_2M_firefly_hanyui_3epoch 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: batch_size : 256 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: per_device_train_batch_size : 16 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: num_epochs : 3 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: learning_rate : 1.5e-05 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: cutoff_len : 1024 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_size : 1500 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_rate : 0.05 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: save_steps : 1000 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: eval_steps : 1000 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: warmup_steps : 200 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: logging_steps : 30 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: gradient_accumulation_steps : 4 2023-04-18 11:16:25 - finetune-mixdata.py[line:328] - INFO: per_device_train_batch_size = 16, gradient_accumulation_steps = 4 Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning. 2023-04-18 11:16:25 - finetune-mixdata.py[line:319] - INFO: args.**dict** : {'model_config_file': 'run_config/Bloom_mix_config.json', 'deepspeed': None, 'resume_from_checkpoint': False, 'train_on_inputs': False, 'lora_hyperparams_file': 'run_config/lora_hyperparams_bloom.json', 'use_lora': True, 'local_rank': None} 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_type : bloom 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: model_name_or_path : bigscience/bloomz-7b1-mt 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: data_path : data_dir/train_2M_CN.json 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: output_dir : trained_models/bloom_2M_firefly_hanyui_3epoch 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: batch_size : 256 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: per_device_train_batch_size : 16 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: num_epochs : 3 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: learning_rate : 1.5e-05 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: cutoff_len : 1024 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_size : 1500 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: val_set_rate : 0.05 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: save_steps : 1000 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: eval_steps : 1000 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: warmup_steps : 200 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: logging_steps : 30 2023-04-18 11:16:25 - finetune-mixdata.py[line:321] - INFO: gradient_accumulation_steps : 4 2023-04-18 11:16:25 - finetune-mixdata.py[line:328] - INFO: per_device_train_batch_size = 16, gradient_accumulation_steps = 4 Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning. Loading checkpoint shards: 0%| | 0/4 [00:00<?, ?it/s]Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning. Loading checkpoint shards: 0%| | 0/4 [00:00<?, ?it/s]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2947 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2948 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2949 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2951 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2952 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2954 closing signal SIGTERM ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 3 (pid: 2950) of binary: /usr/local/anaconda3/bin/python Traceback (most recent call last): File "/usr/local/anaconda3/bin/torchrun", line 8, in sys.exit(main()) File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 345, in wrapper return f(*args, **kwargs) File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 724, in main run(args) File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run elastic_launch( File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in **call** return launch_agent(self._config, self._entrypoint, list(args)) File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent raise ChildFailedError( torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

我们已经更新了代码，可参考最新版代码，基于deepspeed-chat开发，提供了docker环境
