### ISSUE TITLE
TypeError: init_process_group() got multiple values for keyword argument 'backend'

### ISSUE THREAD

**Issue by lixiaoxiaobin** [LianjiaTech/BELLE#403]
训练13b模型时，报这个错误，有人遇到过吗
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "src/train.py", line 393, in <module>
    main()
  File "src/train.py", line 163, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/opt/conda/lib/python3.8/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 114, in __init__
  File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1255, in __post_init__
    and (self.device.type != "cuda")
  File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1618, in device
    return self._setup_devices
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1550, in _setup_devices
    self.distributed_state = PartialState(backend=self.xpu_backend)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/state.py", line 129, in __init__
    torch.distributed.init_process_group(backend="nccl", **kwargs)
TypeError: init_process_group() got multiple values for keyword argument 'backend'
Traceback (most recent call last):
  File "src/train.py", line 393, in <module>
    main()
  File "src/train.py", line 163, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/opt/conda/lib/python3.8/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 114, in __init__
  File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1255, in __post_init__
    and (self.device.type != "cuda")
  File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1618, in device
    return self._setup_devices
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1550, in _setup_devices
    self.distributed_state = PartialState(backend=self.xpu_backend)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/state.py", line 129, in __init__
    torch.distributed.init_process_group(backend="nccl", **kwargs)
TypeError: init_process_group() got multiple values for keyword argument 'backend'

**Comment by xianghuisun** [comment]
> 训练13b模型时，报这个错误，有人遇到过吗 WARNING:torch.distributed.run:
> 
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
> 
> Traceback (most recent call last): File "src/train.py", line 393, in main() File "src/train.py", line 163, in main model_args, data_args, training_args = parser.parse_args_into_dataclasses() File "/opt/conda/lib/python3.8/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses obj = dtype(**inputs) File "", line 114, in **init** File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1255, in **post_init** and (self.device.type != "cuda") File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1618, in device return self._setup_devices File "/opt/conda/lib/python3.8/site-packages/transformers/utils/generic.py", line 54, in **get** cached = self.fget(obj) File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1550, in _setup_devices self.distributed_state = PartialState(backend=self.xpu_backend) File "/opt/conda/lib/python3.8/site-packages/accelerate/state.py", line 129, in **init** torch.distributed.init_process_group(backend="nccl", **kwargs) TypeError: init_process_group() got multiple values for keyword argument 'backend' Traceback (most recent call last): File "src/train.py", line 393, in main() File "src/train.py", line 163, in main model_args, data_args, training_args = parser.parse_args_into_dataclasses() File "/opt/conda/lib/python3.8/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses obj = dtype(**inputs) File "", line 114, in **init** File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1255, in **post_init** and (self.device.type != "cuda") File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1618, in device return self._setup_devices File "/opt/conda/lib/python3.8/site-packages/transformers/utils/generic.py", line 54, in **get** cached = self.fget(obj) File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1550, in _setup_devices self.distributed_state = PartialState(backend=self.xpu_backend) File "/opt/conda/lib/python3.8/site-packages/accelerate/state.py", line 129, in **init** torch.distributed.init_process_group(backend="nccl", **kwargs) TypeError: init_process_group() got multiple values for keyword argument 'backend'

有可能是transformers版本的问题
您是基于我们提供的docker环境运行的嘛，或者您的transformers和pytorch版本是什么

**Comment by lixiaoxiaobin** [comment]
> 有可能是transformers版本的问题
> 您是基于我们提供的docker环境运行的嘛，或者您的transformers和pytorch版本是什么

基于官网docker镜像跑的
>>> import torch
>>> print(torch.__version__)
2.0.0+cu117
>>> import transformers
>>> print(transformers.__version__)
4.29.0.dev0

**Comment by lixiaoxiaobin** [comment]
降低transformers和pytorch版本和train文件下的requirements.txt一样，就可以了，这个docker镜像有点坑呀

**Comment by wygao8** [comment]
我降低了transformers和pytorch版本也不行，最后把train文件下的requirements.txt全部安装了才可以跑。
