### ISSUE TITLE
Indexing the wrong thing while batching input data

### ISSUE THREAD

**Issue by joe-kwon-lg** [LianjiaTech/BELLE#491]
`Grouping texts in chunks of 1024:   2%|▏         | 11000/518255 [00:10<07:39, 1105.10 examples/s]
Grouping texts in chunks of 1024:   2%|▏         | 11000/518255 [00:11<08:33, 988.58 examples/s] 
Traceback (most recent call last):
  File "xxx/BELLE/train/src/entry_point/sft_train.py", line 514, in <module>
    main()
  File "xxx/BELLE/train/src/entry_point/sft_train.py", line 336, in main
    train_data["train"]
  File "xxx/anaconda3/envs/belle/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/xxx/anaconda3/envs/belle/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/xxx/anaconda3/envs/belle/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3097, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/xxx/anaconda3/envs/belle/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3474, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/xxx/anaconda3/envs/belle/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "xxx/BELLE/train/src/sample_generator.py", line 110, in batch_grouped_sft_generate
    labels[18:24] = input_ids[i][18:24]
TypeError: 'int' object is not subscriptable`

I don't understand why 18:24 is hard-coded, what is the purpose of this? Also, why isn't it indexing input_ids_list instead of input_ids? I'm not sure why this error is not happening for anyone else.

**Comment by joe-kwon-lg** [comment]
If you use flash attention, you need to change the code in sample_generator.py from labels[18:24] = input_ids[i][18:24] to labels[18:24] = input_ids_list[i][18:24]
