### ISSUE TITLE
ModuleNotFoundError: No module named 'src'     from src.utils import get_model_param_count

### ISSUE THREAD

**Issue by wengieeee** [LianjiaTech/BELLE#514]
**代码执行路径：**
/data_backup/BELLE/train

**执行命令：**
bash scripts/run_sft.sh

**run_sft.sh 脚本参数修改为**：
#! /bin/bash
export CUDA_VISIBLE_DEVICES='1'
export WANDB_PROJECT=bloomz
export WANDB_RUN_ID=01
export WANDB_RESUME=allow
export ABS_PATH=/data_backup/models/bell
export PYTHONPATH="$ABS_PATH/BELLE/train"
model_name_or_path=/data/deploy/cache/modelscope/AI-ModelScope/bloomz-7b1-mt # or bloomz-7b1-mt

train_file=belleMath.json
validation_file=belleMath-dev1K.json
output_dir="$ABS_PATH/BELLE/saved_models/${WANDB_PROJECT}_${WANDB_RUN_ID}"
mkdir -p ${output_dir}

**报错：**
尝试训练时报错python代码找不到src包

Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/data_backup/models/belle/BELLE/train/src/entry_point/sft_train.py", line 27, in <module>
  File "/data_backup/models/belle/BELLE/train/src/entry_point/sft_train.py", line 27, in <module>
  File "/data_backup/models/belle/BELLE/train/src/entry_point/sft_train.py", line 27, in <module>
Traceback (most recent call last):
        from src.utils import get_model_param_count  File "/data_backup/models/belle/BELLE/train/src/entry_point/sft_train.py", line 27, in <module>
from src.utils import get_model_param_count

ModuleNotFoundErrorModuleNotFoundError: : No module named 'src'    No module named 'src'
from src.utils import get_model_param_count

**Comment by 1181000705** [comment]
怎么解决的？我也遇到一样的问题
