### ISSUE TITLE
LoRA with 8bit报错

### ISSUE THREAD

**Issue by 18liumin** [LianjiaTech/BELLE#516]
[INFO|trainer.py:1721] 2023-09-20 09:37:19,421 >>   Number of trainable parameters = 39,976,960
  0%|                                                                                                                               | 0/270440 [00:00<?, ?it/s]                                                                                                                  /home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes/autograd/_functions.py:322: UserWarning:                                                                                                                   MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes/autograd/_functions.py:322: UserWarning:                                                                                                                   MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes/autograd/_functions.py:322: UserWarning:                                                                                                                   MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes/autograd/_functions.py:322: UserWarning:                                                                                                                   MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes/autograd/_functions.py:322: UserWarning:                                                                                                                   MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes/autograd/_functions.py:322: UserWarning:                                                                                                                   MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes/autograd/_functions.py:322: UserWarning:                                                                                                                   MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes/autograd/_functions.py:322: UserWarning:                                                                                                                   MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
Traceback (most recent call last):
  File "../src/entry_point/pt_train.py", line 494, in <module>
    main()
  File "../src/entry_point/pt_train.py", line 483, in main
    trainer.train(resume_from_checkpoint=checkpoint)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/transformers/trainer.py", line 1835, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/transformers/trainer.py", line 2679, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/transformers/trainer.py", line 2704, in compute_loss
    outputs = model(**inputs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/peft/peft_model.py", line 918, in forward
    return self.base_model(
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 820, in forward
    outputs = self.model(
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 701, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 697, in custom_forward
    return module(*inputs, past_key_value, output_attentions)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 424, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 321, in forward
    query_states = self.q_proj(hidden_states)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/peft/tuners/lora.py", line 1149, in forward
    result = super().forward(x)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes/nn/modules.py", line 441, in for                                                                                                                  ward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes/autograd/_functions.py", line 56                                                                                                                  3, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/home//software/anaconda3/envs/megaton/lib/python3.8/site-packages/bitsandbytes-0.41.1-py3.8.egg/bitsandbytes/autograd/_functions.py", line 41                                                                                                                  4, in forward
    output = torch.nn.functional.linear(A_wo_outliers, state.CB.to(A.dtype))
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

**Comment by 18liumin** [comment]
解决，原因是GPU显存问题，更改了"lora_r": 16, 为 8
