### ISSUE TITLE
预训练报错 NCCL Socket Timeout

### ISSUE THREAD

**Issue by Davidwhw** [LianjiaTech/BELLE#542]
> 单机 4 个 A800
> - Python 3.8.0
> - CUDA : 11.8
> - PyTorch: 2.0.1

Grouping texts 进行到 29% 出现 NCCL 报错 ：`RuntimeError: [2] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout`。 如何解决这个错误？
```
Set the eos_token_id and bos_token_id of LLama model tokenizer
tokenizer.eos_token_id = 2
tokenizer.pad_token_id = 0
tokenizer.bos_token_id = 1
Loading checkpoint shards: 100%|██████████| 2/2 [00:04<00:00,  2.32s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:04<00:00,  2.35s/it]
Grouping texts in chunks of 1024:  29%|██▉       | 3362000/11407235 [10:03:35<25:22:33, 88.07 examples/s]Traceback (most recent call last):
  File "src/entry_point/pt_train.py", line 481, in <module>
    main()
  File "src/entry_point/pt_train.py", line 317, in main
    with torch_distributed_zero_first(global_rank):
  File "/home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/transformers/trainer_pt_utils.py", line 251, in torch_distributed_zero_first
    dist.barrier()
  File "/home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3328, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: [2] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout
Exception raised from recvBytes at /opt/conda/conda-bld/pytorch_1682343998658/work/torch/csrc/distributed/c10d/Utils.hpp:604 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7fe3cc6e34d7 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x68 (0x7fe3cc6ad434 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0xd8 (0x7fe4160f8528 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::TCPStore::doGet(std::string const&) + 0x22 (0x7fe4160f91d2 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #4: c10d::TCPStore::get(std::string const&) + 0x59 (0x7fe4160f9259 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fe4160b8721 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fe4160b8721 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fe4160b8721 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #8: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fe4160b8721 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #9: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x7fe3cd6a5bcf in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #10: c10d::ProcessGroupNCCL::getNCCLComm(std::string const&, std::vector<c10::Device, std::allocator<c10::Device> > const&, c10d::OpType, int, bool) + 0x201 (0x7fe3cd6a9881 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #11: <unknown function> + 0xf039ad (0x7fe3cd6b09ad in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #12: c10d::ProcessGroupNCCL::allreduce_impl(std::vector<at::Tensor, std::allocator<at::Tensor> >&, c10d::AllreduceOptions const&) + 0x21 (0x7fe3cd6b1db1 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #13: c10d::ProcessGroupNCCL::allreduce(std::vector<at::Tensor, std::allocator<at::Tensor> >&, c10d::AllreduceOptions const&) + 0x39d (0x7fe3cd6b4a6d in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #14: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x851 (0x7fe3cd6c39c1 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #15: <unknown function> + 0x501cf39 (0x7fe4160acf39 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x5020c8a (0x7fe4160b0c8a in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x502faf0 (0x7fe4160bfaf0 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #18: <unknown function> + 0xb6b55e (0x7fe41fc2d55e in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #19: <unknown function> + 0x3b7040 (0x7fe41f479040 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #20: PyCFunction_Call + 0x56 (0x55a9abd0ec96 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #21: _PyObject_MakeTpCall + 0x22f (0x55a9abccb31f in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #22: <unknown function> + 0x18227c (0x55a9abd1b27c in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #23: <unknown function> + 0xfa6c1 (0x55a9abc936c1 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #24: <unknown function> + 0x2023ed (0x55a9abd9b3ed in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #25: <unknown function> + 0xfb37e (0x55a9abc9437e in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #26: <unknown function> + 0x20feb6 (0x55a9abda8eb6 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #27: <unknown function> + 0x17a8a3 (0x55a9abd138a3 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #28: <unknown function> + 0x135359 (0x55a9abcce359 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #29: <unknown function> + 0xfb3cc (0x55a9abc943cc in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #30: _PyFunction_Vectorcall + 0x10b (0x55a9abd1ab1b in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #31: <unknown function> + 0x18219d (0x55a9abd1b19d in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #32: <unknown function> + 0x7b098 (0x55a9abc14098 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x2002 (0x55a9abd544c2 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #34: _PyFunction_Vectorcall + 0x10b (0x55a9abd1ab1b in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #35: <unknown function> + 0xfb3cc (0x55a9abc943cc in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #36: _PyEval_EvalCodeWithName + 0x2d2 (0x55a9abd19c32 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #37: PyEval_EvalCodeEx + 0x44 (0x55a9abd1aa04 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #38: PyEval_EvalCode + 0x1c (0x55a9abdadf5c in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #39: <unknown function> + 0x215004 (0x55a9abdae004 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #40: <unknown function> + 0x24a304 (0x55a9abde3304 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #41: PyRun_FileExFlags + 0xa0 (0x55a9abde5c50 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #42: PyRun_SimpleFileExFlags + 0x1c1 (0x55a9abde5e41 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #43: Py_RunMain + 0x313 (0x55a9abde6983 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #44: Py_BytesMain + 0x39 (0x55a9abde6bc9 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
frame #45: __libc_start_main + 0xf3 (0x7fe479017083 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #46: <unknown function> + 0x1d6e13 (0x55a9abd6fe13 in /home/wanghw/miniconda3/envs/llm_torch_2.0.1/bin/python)
. This may indicate a possible application crash on rank 0 or a network set up issue.
```

**Comment by cxfzzj** [comment]
一样遇到了，上面的网友你解决了吗？

**Comment by Davidwhw** [comment]
> 一样遇到了，上面的网友你解决了吗？

数据预处理的时间过长，超出了pytorch进程的存活时间。建议将数据预处理环节单独提出，将处理完的数据使用 datasets 的对应函数保存在本地即可。
