### ISSUE TITLE
deepspeed warmup_num_steps:"Auto" 报错

### ISSUE THREAD

**Issue by zhxchnl** [LianjiaTech/BELLE#558]
运行了 train/scripts/run_dpo.sh

报错信息如下：
Traceback (most recent call last):
  File "/zhongxiaochao/BELLE/train/src/entry_point/dpo_train_my.py", line 355, in <module>
    main()
  File "/zhongxiaochao/BELLE/train/src/entry_point/dpo_train_my.py", line 308, in main
    dpo_trainer = CustomDPOTrainer(
  File "/home/deepspeed/miniconda3/envs/py39/lib/python3.9/site-packages/trl/trainer/dpo_trainer.py", line 342, in __init__
    self.ref_model = self._prepare_deepspeed(self.ref_model)
  File "/home/deepspeed/miniconda3/envs/py39/lib/python3.9/site-packages/trl/trainer/dpo_trainer.py", line 375, in _prepare_deepspeed
    model, *_ = deepspeed.initialize(model=model, config=config_kwargs)
  File "/home/deepspeed/miniconda3/envs/py39/lib/python3.9/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/deepspeed/miniconda3/envs/py39/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 305, in __init__
    self._configure_lr_scheduler(lr_scheduler)
  File "/home/deepspeed/miniconda3/envs/py39/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 891, in _configure_lr_scheduler
    lr_scheduler = self._scheduler_from_config(self.optimizer)
  File "/home/deepspeed/miniconda3/envs/py39/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 946, in _scheduler_from_config
    instantiated_scheduler = scheduler(optimizer, **scheduler_params)
  File "/home/deepspeed/miniconda3/envs/py39/lib/python3.9/site-packages/deepspeed/runtime/lr_schedules.py", line 756, in __init__
    super(WarmupDecayLR, self).__init__(optimizer, warmup_min_lr, warmup_max_lr, warmup_num_steps, warmup_type,
  File "/home/deepspeed/miniconda3/envs/py39/lib/python3.9/site-packages/deepspeed/runtime/lr_schedules.py", line 669, in __init__
    self.warmup_num_steps = max(2, warmup_num_steps)
TypeError: '>' not supported between instances of 'str' and 'int'

打印了 site-packages/trl/trainer/dpo_trainer.py   def _prepare_deepspeed  中的config_kwargs。看起来似乎是deepspeed启动的时候的warmup任然是auto不是数字导致的问题。
{'bfloat16': {'enabled': True}, 'fp16': {'enabled': False, 'loss_scale': 0, 'loss_scale_window': 1000, 'initial_scale_power': 16, 'hysteresis': 2, 'min_loss_scale': 1}, 'optimizer': {'type': 'AdamW', 'params': {'lr': 1e-05, 'weight_decay': 0.0001, 'betas': [0.9, 0.999], 'eps': 1e-08, 'torch_adam': True, 'adam_w_mode': True}}, 'scheduler': {'type': 'WarmupDecayLR', 'params': {'warmup_min_lr': 0, 'warmup_max_lr': 1e-05, 'warmup_num_steps': 'auto', 'total_num_steps': 'auto'}}, 'zero_optimization': {'stage': 3, 'overlap_comm': True, 'contiguous_gradients': True, 'sub_group_size': 1000000000000.0, 'reduce_bucket_size': 'auto', 'stage3_prefetch_bucket_size': 'auto', 'stage3_param_persistence_threshold': 'auto', 'stage3_max_live_parameters': 1000000000.0, 'stage3_max_reuse_distance': 1000000000.0, 'stage3_gather_16bit_weights_on_model_save': True}, 'gradient_accumulation_steps': 1, 'gradient_clipping': 1.0, 'steps_per_print': inf, 'train_batch_size': 4, 'train_micro_batch_size_per_gpu': 1, 'wall_clock_breakdown': False, 'bf16': {'enabled': True}, 'zero_optimization.reduce_bucket_size': 16777216, 'zero_optimization.stage3_param_persistence_threshold': 40960, 'zero_optimization.stage3_prefetch_bucket_size': 15099494.4}

**Comment by zhxchnl** [comment]
另外，deepspeed json里面设置的warm up step和run_dpo.sh 里面的 warm up ratio似乎没有关系？

**Comment by Emperorizzis** [comment]
感谢您的提问。

我们并没有遇到您提到的问题。请您尝试将`Transformers`、`deepspeed`更新到最新版本再尝试运行脚本，或提供更详细的报错信息。

另外，我们实现的DPO训练脚本中的warmup ratio会计算出所需warmup steps，并传入Transformers，Transformers内部会传入Deepspeed.

**Comment by zhxchnl** [comment]
> 感谢您的提问。
> 
> 我们并没有遇到您提到的问题。请您尝试将`Transformers`、`deepspeed`更新到最新版本再尝试运行脚本，或提供更详细的报错信息。
> 
> 另外，我们实现的DPO训练脚本中的warmup ratio会计算出所需warmup steps，并传入Transformers，Transformers内部会传入Deepspeed.

可能是deepspeed版本的问题，我的版本是0.12.3。在deepspeed initial的时候会检查optimizer的参数，而auto的参数填充是在train阶段才会被transformer deepspeed填充上。造成了initial的时候会检查optimizer的参数的错误

**Comment by Zhouxinyu668** [comment]
> > 感谢您的提问。
> > 我们并没有遇到您提到的问题。请您尝试将`Transformers`、`deepspeed`更新到最新版本再尝试运行脚本，或提供更详细的报错信息。
> > 另外，我们实现的DPO训练脚本中的warmup ratio会计算出所需warmup steps，并传入Transformers，Transformers内部会传入Deepspeed.
> 
> 可能是deepspeed版本的问题，我的版本是0.12.3。在deepspeed initial的时候会检查optimizer的参数，而auto的参数填充是在train阶段才会被transformer deepspeed填充上。造成了initial的时候会检查optimizer的参数的错误

你好，我想问一下，最后你是怎么解决的这个问题？

**Comment by zhxchnl** [comment]
> > > 感谢您的提问。
> > > 我们并没有遇到您提到的问题。请您尝试将`Transformers`、`deepspeed`更新到最新版本再尝试运行脚本，或提供更详细的报错信息。
> > > 另外，我们实现的DPO训练脚本中的warmup ratio会计算出所需warmup steps，并传入Transformers，Transformers内部会传入Deepspeed.
> > 
> > 
> > 可能是deepspeed版本的问题，我的版本是0.12.3。在deepspeed initial的时候会检查optimizer的参数，而auto的参数填充是在train阶段才会被transformer deepspeed填充上。造成了initial的时候会检查optimizer的参数的错误
> 
> 你好，我想问一下，最后你是怎么解决的这个问题？

最后是凭经验设置的数值，没有使用“auto”。
