### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by XY2323819551** [LianjiaTech/BELLE#91]
我在按照命令进行lora微调的时候，为什么总是报上述错误呢？我该如何如何改正呢？``

**Comment by XY2323819551** [comment]
> 我在按照命令进行lora微调的时候，为什么总是报上述错误呢？我该如何如何改正呢？``

但是我如果用您发布的模型代替hf模型，就可以正常运行了。

**Comment by scarydemon2** [comment]
调bloomz的时候会有同样的错误，alpaca-lora，alpaca-Cot和BELLE上面都会报这个错误。有无好心人告诉怎么解决

**Comment by LiuChen19960902** [comment]
我用的时候也是，实际上我自己写amp是可以用fp16的，但是不知道为什么用Trainer训练时候，fp16为True就会有这样的问题。但是最难受的是，只有bloom会出现这样的问题......  llama并不会

**Comment by xianghuisun** [comment]
> > 我在按照命令进行lora微调的时候，为什么总是报上述错误呢？我该如何如何改正呢？``
> 
> 但是我如果用您发布的模型代替hf模型，就可以正常运行了。

您好，配置文件中的model_name_or_path是huggingface原生的模型，我们本地训练也是使用的这个模型，并没有报错。您能把运行的启动命令和报错信息的位置发下吗，我们更容易定位原因。

**Comment by leerelive** [comment]
python generate.py --dev_file data_dir/Belle_open_source_0.5M.dev.json \
--model_name_or_path pretrained_model/bloomz-7b1-mt \
--output_file data_dir/predictions_belle_0.5.json \
--lora_weights trained_models/bloom


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
  0%|                                                   | 0/10 [00:00<?, ?batch/s]
╭────────────────────── Traceback (most recent call last) ───────────────────────╮
│ /data/guest/llm/BELLE/train/generate.py:138 in <module>                        │
│                                                                                │
│   135 │   tokenizer = AutoTokenizer.from_pretrained(args.model_name_or_path)   │
│   136 │   # model = AutoModelForCausalLM.from_pretrained(args.model_name_or_pa │
│   137 │   model = get_model(args.model_name_or_path)                           │
│ ❱ 138 │   main(args)                                                           │
│   139                                                                          │
│                                                                                │
│ /data/guest/llm/BELLE/train/generate.py:118 in main                            │
│                                                                                │
│   115                                                                          │
│   116 def main(args):                                                          │
│   117 │   dev_data = load_dev_data(args.dev_file)[:10]#For simplify and save t │
│ ❱ 118 │   res = generate_text(dev_data, batch_size, tokenizer, model)          │
│   119 │   with open(args.output_file, 'w') as f:                               │
│   120 │   │   json.dump(res, f, ensure_ascii=False, indent=4)                  │
│   121                                                                          │
│                                                                                │
│ /data/guest/llm/BELLE/train/generate.py:94 in generate_text                    │
│                                                                                │
│    91 │   │   input_ids = features['input_ids'].to("cuda")                     │
│    92 │   │   attention_mask = features['attention_mask'].to("cuda")           │
│    93 │   │                                                                    │
│ ❱  94 │   │   output_texts = model.generate(                                   │
│    95 │   │   │   input_ids=input_ids,                                         │
│    96 │   │   │   attention_mask=attention_mask,                               │
│    97 │   │   │   num_beams = 4,                                               │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/peft-0.3.0.dev0-py3.10.egg/peft/ │
│ peft_model.py:627 in generate                                                  │
│                                                                                │
│ [Errno 20] Not a directory:                                                    │
│ '/root/miniconda3/lib/python3.10/site-packages/peft-0.3.0.dev0-py3.10.egg/peft │
│ /peft_model.py'                                                                │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py:27   │
│ in decorate_context                                                            │
│                                                                                │
│    24 │   │   @functools.wraps(func)                                           │
│    25 │   │   def decorate_context(*args, **kwargs):                           │
│    26 │   │   │   with self.clone():                                           │
│ ❱  27 │   │   │   │   return func(*args, **kwargs)                             │
│    28 │   │   return cast(F, decorate_context)                                 │
│    29 │                                                                        │
│    30 │   def _wrap_generator(self, func):                                     │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/transformers-4.28.0.dev0-py3.10. │
│ egg/transformers/generation/utils.py:1524 in generate                          │
│                                                                                │
│   1521 │   │   │   │   **model_kwargs,                                         │
│   1522 │   │   │   )                                                           │
│   1523 │   │   │   # 13. run beam search                                       │
│ ❱ 1524 │   │   │   return self.beam_search(                                    │
│   1525 │   │   │   │   input_ids,                                              │
│   1526 │   │   │   │   beam_scorer,                                            │
│   1527 │   │   │   │   logits_processor=logits_processor,                      │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/transformers-4.28.0.dev0-py3.10. │
│ egg/transformers/generation/utils.py:2810 in beam_search                       │
│                                                                                │
│   2807 │   │   │                                                               │
│   2808 │   │   │   model_inputs = self.prepare_inputs_for_generation(input_ids │
│   2809 │   │   │                                                               │
│ ❱ 2810 │   │   │   outputs = self(                                             │
│   2811 │   │   │   │   **model_inputs,                                         │
│   2812 │   │   │   │   return_dict=True,                                       │
│   2813 │   │   │   │   output_attentions=output_attentions,                    │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py:1190  │
│ in _call_impl                                                                  │
│                                                                                │
│   1187 │   │   # this function, and just call forward.                         │
│   1188 │   │   if not (self._backward_hooks or self._forward_hooks or self._fo │
│   1189 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks): │
│ ❱ 1190 │   │   │   return forward_call(*input, **kwargs)                       │
│   1191 │   │   # Do not call functions when jit is used                        │
│   1192 │   │   full_backward_hooks, non_full_backward_hooks = [], []           │
│   1193 │   │   if self._backward_hooks or _global_backward_hooks:              │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py:158 in       │
│ new_forward                                                                    │
│                                                                                │
│   155 │   │   │   with torch.no_grad():                                        │
│   156 │   │   │   │   output = old_forward(*args, **kwargs)                    │
│   157 │   │   else:                                                            │
│ ❱ 158 │   │   │   output = old_forward(*args, **kwargs)                        │
│   159 │   │   return module._hf_hook.post_forward(module, output)              │
│   160 │                                                                        │
│   161 │   module.forward = new_forward                                         │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/transformers-4.28.0.dev0-py3.10. │
│ egg/transformers/models/bloom/modeling_bloom.py:913 in forward                 │
│                                                                                │
│    910 │   │                                                                   │
│    911 │   │   return_dict = return_dict if return_dict is not None else self. │
│    912 │   │                                                                   │
│ ❱  913 │   │   transformer_outputs = self.transformer(                         │
│    914 │   │   │   input_ids,                                                  │
│    915 │   │   │   past_key_values=past_key_values,                            │
│    916 │   │   │   attention_mask=attention_mask,                              │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py:1190  │
│ in _call_impl                                                                  │
│                                                                                │
│   1187 │   │   # this function, and just call forward.                         │
│   1188 │   │   if not (self._backward_hooks or self._forward_hooks or self._fo │
│   1189 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks): │
│ ❱ 1190 │   │   │   return forward_call(*input, **kwargs)                       │
│   1191 │   │   # Do not call functions when jit is used                        │
│   1192 │   │   full_backward_hooks, non_full_backward_hooks = [], []           │
│   1193 │   │   if self._backward_hooks or _global_backward_hooks:              │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/transformers-4.28.0.dev0-py3.10. │
│ egg/transformers/models/bloom/modeling_bloom.py:786 in forward                 │
│                                                                                │
│    783 │   │   │   │   │   head_mask[i],                                       │
│    784 │   │   │   │   )                                                       │
│    785 │   │   │   else:                                                       │
│ ❱  786 │   │   │   │   outputs = block(                                        │
│    787 │   │   │   │   │   hidden_states,                                      │
│    788 │   │   │   │   │   layer_past=layer_past,                              │
│    789 │   │   │   │   │   attention_mask=causal_mask,                         │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py:1190  │
│ in _call_impl                                                                  │
│                                                                                │
│   1187 │   │   # this function, and just call forward.                         │
│   1188 │   │   if not (self._backward_hooks or self._forward_hooks or self._fo │
│   1189 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks): │
│ ❱ 1190 │   │   │   return forward_call(*input, **kwargs)                       │
│   1191 │   │   # Do not call functions when jit is used                        │
│   1192 │   │   full_backward_hooks, non_full_backward_hooks = [], []           │
│   1193 │   │   if self._backward_hooks or _global_backward_hooks:              │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py:158 in       │
│ new_forward                                                                    │
│                                                                                │
│   155 │   │   │   with torch.no_grad():                                        │
│   156 │   │   │   │   output = old_forward(*args, **kwargs)                    │
│   157 │   │   else:                                                            │
│ ❱ 158 │   │   │   output = old_forward(*args, **kwargs)                        │
│   159 │   │   return module._hf_hook.post_forward(module, output)              │
│   160 │                                                                        │
│   161 │   module.forward = new_forward                                         │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/transformers-4.28.0.dev0-py3.10. │
│ egg/transformers/models/bloom/modeling_bloom.py:439 in forward                 │
│                                                                                │
│    436 │   │   │   residual = hidden_states                                    │
│    437 │   │                                                                   │
│    438 │   │   # Self attention.                                               │
│ ❱  439 │   │   attn_outputs = self.self_attention(                             │
│    440 │   │   │   layernorm_output,                                           │
│    441 │   │   │   residual,                                                   │
│    442 │   │   │   layer_past=layer_past,                                      │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py:1190  │
│ in _call_impl                                                                  │
│                                                                                │
│   1187 │   │   # this function, and just call forward.                         │
│   1188 │   │   if not (self._backward_hooks or self._forward_hooks or self._fo │
│   1189 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks): │
│ ❱ 1190 │   │   │   return forward_call(*input, **kwargs)                       │
│   1191 │   │   # Do not call functions when jit is used                        │
│   1192 │   │   full_backward_hooks, non_full_backward_hooks = [], []           │
│   1193 │   │   if self._backward_hooks or _global_backward_hooks:              │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py:158 in       │
│ new_forward                                                                    │
│                                                                                │
│   155 │   │   │   with torch.no_grad():                                        │
│   156 │   │   │   │   output = old_forward(*args, **kwargs)                    │
│   157 │   │   else:                                                            │
│ ❱ 158 │   │   │   output = old_forward(*args, **kwargs)                        │
│   159 │   │   return module._hf_hook.post_forward(module, output)              │
│   160 │                                                                        │
│   161 │   module.forward = new_forward                                         │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/transformers-4.28.0.dev0-py3.10. │
│ egg/transformers/models/bloom/modeling_bloom.py:290 in forward                 │
│                                                                                │
│    287 │   │   use_cache: bool = False,                                        │
│    288 │   │   output_attentions: bool = False,                                │
│    289 │   ):                                                                  │
│ ❱  290 │   │   fused_qkv = self.query_key_value(hidden_states)  # [batch_size, │
│    291 │   │                                                                   │
│    292 │   │   # 3 x [batch_size, seq_length, num_heads, head_dim]             │
│    293 │   │   (query_layer, key_layer, value_layer) = self._split_heads(fused │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py:1190  │
│ in _call_impl                                                                  │
│                                                                                │
│   1187 │   │   # this function, and just call forward.                         │
│   1188 │   │   if not (self._backward_hooks or self._forward_hooks or self._fo │
│   1189 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks): │
│ ❱ 1190 │   │   │   return forward_call(*input, **kwargs)                       │
│   1191 │   │   # Do not call functions when jit is used                        │
│   1192 │   │   full_backward_hooks, non_full_backward_hooks = [], []           │
│   1193 │   │   if self._backward_hooks or _global_backward_hooks:              │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py:158 in       │
│ new_forward                                                                    │
│                                                                                │
│   155 │   │   │   with torch.no_grad():                                        │
│   156 │   │   │   │   output = old_forward(*args, **kwargs)                    │
│   157 │   │   else:                                                            │
│ ❱ 158 │   │   │   output = old_forward(*args, **kwargs)                        │
│   159 │   │   return module._hf_hook.post_forward(module, output)              │
│   160 │                                                                        │
│   161 │   module.forward = new_forward                                         │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/peft-0.3.0.dev0-py3.10.egg/peft/ │
│ tuners/lora.py:530 in forward                                                  │
│                                                                                │
│ [Errno 20] Not a directory:                                                    │
│ '/root/miniconda3/lib/python3.10/site-packages/peft-0.3.0.dev0-py3.10.egg/peft │
│ /tuners/lora.py'                                                               │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py:1190  │
│ in _call_impl                                                                  │
│                                                                                │
│   1187 │   │   # this function, and just call forward.                         │
│   1188 │   │   if not (self._backward_hooks or self._forward_hooks or self._fo │
│   1189 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks): │
│ ❱ 1190 │   │   │   return forward_call(*input, **kwargs)                       │
│   1191 │   │   # Do not call functions when jit is used                        │
│   1192 │   │   full_backward_hooks, non_full_backward_hooks = [], []           │
│   1193 │   │   if self._backward_hooks or _global_backward_hooks:              │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py:158 in       │
│ new_forward                                                                    │
│                                                                                │
│   155 │   │   │   with torch.no_grad():                                        │
│   156 │   │   │   │   output = old_forward(*args, **kwargs)                    │
│   157 │   │   else:                                                            │
│ ❱ 158 │   │   │   output = old_forward(*args, **kwargs)                        │
│   159 │   │   return module._hf_hook.post_forward(module, output)              │
│   160 │                                                                        │
│   161 │   module.forward = new_forward                                         │
│                                                                                │
│ /root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/linear.py:114   │
│ in forward                                                                     │
│                                                                                │
│   111 │   │   │   init.uniform_(self.bias, -bound, bound)                      │
│   112 │                                                                        │
│   113 │   def forward(self, input: Tensor) -> Tensor:                          │
│ ❱ 114 │   │   return F.linear(input, self.weight, self.bias)                   │
│   115 │                                                                        │
│   116 │   def extra_repr(self) -> str:                                         │
│   117 │   │   return 'in_features={}, out_features={}, bias={}'.format(        │
╰────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: expected scalar type Half but found Float

**Comment by xianghuisun** [comment]
> 调bloomz的时候会有同样的错误，alpaca-lora，alpaca-Cot和BELLE上面都会报这个错误。有无好心人告诉怎么解决

**RuntimeError: expected scalar type Half but found Float**

在跑Bloom模型时，可能会遇到这个问题。经过我们的实验，有如下结论：

- 如果显卡是A100，不会出现expected scalar type Half but found Float的问题，Bloom和Llama都可以跑起来
- 如果显卡是V100，可以跑起来Llama模型，但是Bloom模型就会出现这个错误，此时需要把代码中fp16改为False，才能跑Bloom模型

**Comment by felixstander** [comment]
使用transformers的trainer进行训练的时候，当不开fp16=True的时候，是可以train起来的，但是跑着跑着loss会变成0。我认为是在使用prepare model for int8 training的时候需要调整layer norm的数据类型到float32，为了训练的稳定性。而在调整layernorm到float32后，就会出现expected scalar type half but found float。（bloom里的LayerNorm叫layernorm而不是layer_norm）

**Comment by felixstander** [comment]
顺便想问问作者是使用8卡A100 40G进行zero stage2的finetune吗?显存的占用是怎么样的呀？想问问8卡 v100 16G有可能跑起来吗

**Comment by LiuChen19960902** [comment]
> > 调bloomz的时候会有同样的错误，alpaca-lora，alpaca-Cot和BELLE上面都会报这个错误。有无好心人告诉怎么解决
> 
> **RuntimeError: expected scalar type Half but found Float**
> 
> 在跑Bloom模型时，可能会遇到这个问题。经过我们的实验，有如下结论：
> 
> * 如果显卡是A100，不会出现expected scalar type Half but found Float的问题，Bloom和Llama都可以跑起来
> * 如果显卡是V100，可以跑起来Llama模型，但是Bloom模型就会出现这个错误，此时需要把代码中fp16改为False，才能跑Bloom模型

破案了，我确实是v100上面

**Comment by shaomai00** [comment]
请教：
使用LLama原始weights+官方convert_llama_weights_to_hf.py脚本得到的weights，+lora训练，训练阶段不报错，预测阶段报错：
Traceback (most recent call last):
  File "generate.py", line 143, in <module>
    main(args)
  File "generate.py", line 120, in main
    res = generate_text(dev_data, batch_size, tokenizer, model)
  File "generate.py", line 96, in generate_text
……
RuntimeError: expected scalar type Half but found Float
这时应该在哪里修改FP16呢？

**Comment by bittteerr** [comment]
> 请教： 使用LLama原始weights+官方convert_llama_weights_to_hf.py脚本得到的weights，+lora训练，训练阶段不报错，预测阶段报错： Traceback (most recent call last): File "generate.py", line 143, in main(args) File "generate.py", line 120, in main res = generate_text(dev_data, batch_size, tokenizer, model) File "generate.py", line 96, in generate_text …… RuntimeError: expected scalar type Half but found Float 这时应该在哪里修改FP16呢？

同样的问题，bloom在做generate的时候报错，3090。

**Comment by LiuChen19960902** [comment]
> > 调bloomz的时候会有同样的错误，alpaca-lora，alpaca-Cot和BELLE上面都会报这个错误。有无好心人告诉怎么解决
> 
> 破案了，我之前用的P40，换了A100能用了

A100哪里来的，穷人家的孩子表示很羡慕

**Comment by scarydemon2** [comment]
> > > 调bloomz的时候会有同样的错误，alpaca-lora，alpaca-Cot和BELLE上面都会报这个错误。有无好心人告诉怎么解决
> > 
> > 
> > 破案了，我之前用的P40，换了A100能用了
> 
> A100哪里来的，穷人家的孩子表示很羡慕

hhh，都是公司的，搞了8张A100测试

**Comment by xianghuisun** [comment]
> 

解决办法是在tokenizer前加上with torch.autocast("cuda"):
如：
        with torch.autocast("cuda"):
            features = tokenizer(batch_text, padding=True, return_tensors="pt", truncation=True, max_length = args.max_length)
            input_ids = features['input_ids'].to("cuda")
            attention_mask = features['attention_mask'].to("cuda")

已在generate.py中修复

**Comment by xianghuisun** [comment]
> 解决办法是在tokenizer前加上with torch.autocast("cuda"): 如： with torch.autocast("cuda"): features = tokenizer(batch_text, padding=True, return_tensors="pt", truncation=True, max_length = args.max_length) input_ids = features['input_ids'].to("cuda") attention_mask = features['attention_mask'].to("cuda")
> 
> 已在generate.py中修复

**Comment by Ma-Dan** [comment]
> > 
> 
> 解决办法是在tokenizer前加上with torch.autocast("cuda"): 如： with torch.autocast("cuda"): features = tokenizer(batch_text, padding=True, return_tensors="pt", truncation=True, max_length = args.max_length) input_ids = features['input_ids'].to("cuda") attention_mask = features['attention_mask'].to("cuda")
> 
> 已在generate.py中修复

除了这3句，还要把model.generate和tokenizer.batch_decode两句也都放在with torch.autocast("cuda"):下。

**Comment by Whoolly** [comment]
> 使用transformers的trainer进行训练的时候，当不开fp16=True的时候，是可以train起来的，但是跑着跑着loss会变成0。我认为是在使用prepare model for int8 training的时候需要调整layer norm的数据类型到float32，为了训练的稳定性。而在调整layernorm到float32后，就会出现expected scalar type half but found float。（bloom里的LayerNorm叫layernorm而不是layer_norm）

我参考项目代码设置fp16=Fasle单机多卡训练bloom lora可以跑的起来，但是跑着loss变成0和nan没法收敛。请问下你找到解决方法了吗

**Comment by zgu293** [comment]
> 

有没有找到解决办法啊

**Comment by zgu293** [comment]
> 使用transformers的trainer进行训练的时候，当不开fp16=True的时候，是可以train起来的，但是跑着跑着loss会变成0。我认为是在使用prepare model for int8 training的时候需要调整layer norm的数据类型到float32，为了训练的稳定性。而在调整layernorm到float32后，就会出现expected scalar type half but found float。（bloom里的LayerNorm叫layernorm而不是layer_norm）

有没有找到解决办法啊，可以分享一下吗

**Comment by liang-shihao** [comment]
model = model.half().cuda()

**Comment by ZionDoki** [comment]
> model = model.half().cuda()
我使用 huggingface Trainer 在 fp16=True 模式下多卡训练报 HALF and Float 错误，通过加 model.half() 解决了问题，希望对其他人有帮助。
